import { LIGHT_PALETTE, LIGHT_ROLES, MATERIAL_KEYS, normalizeLevelDef, point, pose, shadowLane } from './LevelDef.js';

export const level01_Archives = normalizeLevelDef({
  id: 'level01_archives',
  title: 'Level 01 - Archives Atrium',
  brief: 'A vertical records atrium where amber stair wells and cold mezzanine spill reveal the route before the stacks do.',
  bounds: { w: 26, d: 24, h: 8.4 },
  extract: point(10.8, 0, -9.4),
  spawn: {
    p0: pose(-10.6, 0, 9.1, -0.72),
    p1: pose(-9.1, 0, 8.4, -0.62),
  },
  lights: [
    {
      id: 'archives-entry-fill',
      x: -9.8,
      y: 3.15,
      z: 6.9,
      target: point(-8.2, 0.04, 5.2),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 13.5,
      range: 8.2,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'archives-atrium-key',
      x: -1.1,
      y: 7.85,
      z: 1.1,
      target: point(0.2, 0.04, 0.1),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 22,
      range: 12.5,
      breakable: true,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'archives-stair-trap',
      x: -6.4,
      y: 5.2,
      z: -2.8,
      target: point(-5.0, 0.04, -2.0),
      color: LIGHT_PALETTE.hotSodiumAmber,
      intensity: 17,
      range: 8.5,
      breakable: true,
      role: LIGHT_ROLES.trap,
    },
    {
      id: 'archives-west-mezz-fill',
      x: -10.3,
      y: 5.85,
      z: -6.9,
      target: point(-8.3, 3.12, -6.1),
      color: LIGHT_PALETTE.dimBlueGray,
      intensity: 9.5,
      range: 7.2,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'archives-east-mezz-key',
      x: 7.9,
      y: 5.85,
      z: -5.9,
      target: point(8.6, 3.12, -4.3),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 15.5,
      range: 8.6,
      breakable: true,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'archives-green-index-glow',
      x: 6.7,
      y: 1.55,
      z: 4.8,
      color: LIGHT_PALETTE.dirtyGreenBlack,
      intensity: 4.8,
      range: 5.3,
      breakable: false,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'archives-extract-amber',
      x: 10.7,
      y: 2.55,
      z: -8.8,
      target: point(10.8, 0.04, -9.4),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 10.5,
      range: 6.5,
      breakable: false,
      role: LIGHT_ROLES.key,
    },
  ],
  shadowLanes: [
    shadowLane(point(-10.6, 0, 9.1), point(-6.5, 0, 4.2), 'entry shadow behind collapsed index shelves'),
    shadowLane(point(-6.5, 0, 4.2), point(1.8, 0, -2.7), 'central atrium dead strip under the amber cone'),
    shadowLane(point(1.8, 0, -2.7), point(9.8, 0, -8.1), 'east stacks to extract without crossing the mezzanine key'),
  ],
  geometry: [
    { type: 'floor', id: 'archives-floor', x: 0, y: 0, z: 0, w: 26, d: 24, material: MATERIAL_KEYS.floor },
    { type: 'box', id: 'archives-ceiling-grid', x: 0, y: 8.48, z: 0, w: 26, h: 0.16, d: 24, material: MATERIAL_KEYS.darkWall },
    { type: 'box', id: 'archives-west-wall', x: -13.15, y: 4.1, z: 0, w: 0.3, h: 8.2, d: 24.4, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'archives-east-wall', x: 13.15, y: 4.1, z: 0, w: 0.3, h: 8.2, d: 24.4, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'archives-north-wall', x: 0, y: 4.1, z: -12.15, w: 26, h: 8.2, d: 0.3, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'archives-south-wall-left', x: -7.9, y: 4.1, z: 12.15, w: 10.2, h: 8.2, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'archives-south-wall-right', x: 8.0, y: 4.1, z: 12.15, w: 10.0, h: 8.2, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'archives-south-door-lintel', x: 0, y: 5.65, z: 12.15, w: 5.8, h: 5.1, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'archives-atrium-pillar-nw', x: -3.6, y: 4.1, z: -3.2, w: 0.58, h: 8.2, d: 0.58, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'archives-atrium-pillar-ne', x: 3.6, y: 4.1, z: -3.2, w: 0.58, h: 8.2, d: 0.58, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'archives-atrium-pillar-sw', x: -3.6, y: 4.1, z: 3.2, w: 0.58, h: 8.2, d: 0.58, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'archives-atrium-pillar-se', x: 3.6, y: 4.1, z: 3.2, w: 0.58, h: 8.2, d: 0.58, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'catwalk', id: 'archives-west-catwalk', x: -8.5, y: 3.12, z: -3.2, w: 6.2, d: 12.8, yaw: 0, material: MATERIAL_KEYS.steel },
    { type: 'catwalk', id: 'archives-east-catwalk', x: 8.3, y: 3.12, z: -3.2, w: 6.2, d: 12.8, yaw: 0, material: MATERIAL_KEYS.steel },
    { type: 'catwalk', id: 'archives-north-bridge', x: 0, y: 3.12, z: -8.8, w: 12.8, d: 2.15, yaw: 0, material: MATERIAL_KEYS.steel },
    { type: 'stairs', id: 'archives-lower-stairs', x: -6.6, y: 0, z: 1.6, w: 2.2, h: 3.12, d: 7.6, yaw: 0.38, steps: 11, material: MATERIAL_KEYS.blackSteel },
    { type: 'stairs', id: 'archives-upper-stairs', x: 6.3, y: 3.12, z: -3.2, w: 2.0, h: 2.65, d: 6.6, yaw: -0.32, steps: 9, material: MATERIAL_KEYS.blackSteel },
    { type: 'box', id: 'archives-stack-a', x: -9.2, y: 1.15, z: 3.5, w: 1.2, h: 2.3, d: 5.6, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'archives-stack-b', x: -6.4, y: 1.15, z: 6.2, w: 4.8, h: 2.3, d: 1.1, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'archives-stack-c', x: 6.8, y: 1.15, z: 4.6, w: 1.1, h: 2.3, d: 5.8, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'archives-stack-d', x: 9.7, y: 1.1, z: 1.5, w: 1.1, h: 2.2, d: 4.3, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'archives-fallen-shelf', x: -2.0, y: 0.48, z: 5.6, w: 4.2, h: 0.75, d: 1.0, yaw: -0.38, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'archives-index-desk', x: 5.8, y: 0.52, z: 7.4, w: 4.2, h: 1.04, d: 1.35, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'archives-extract-frame-left', x: 9.85, y: 1.25, z: -10.65, w: 0.2, h: 2.5, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'archives-extract-frame-right', x: 11.75, y: 1.25, z: -10.65, w: 0.2, h: 2.5, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
  ],
  patrols: [
    [
      point(-8.8, 0, 5.8),
      point(-2.8, 0, 1.8),
      point(4.6, 0, 0.4),
      point(8.4, 0, -6.8),
      point(1.8, 0, -8.2),
      point(-6.8, 0, -4.8),
    ],
  ],
  coverPoints: [
    point(-9.5, 0, 4.8),
    point(-3.3, 0, 5.9),
    point(5.5, 0, 5.3),
    point(9.2, 0, 1.1),
    point(8.5, 0, -7.3),
  ],
  shadowPoints: [
    point(-10.8, 0, 6.6),
    point(-4.1, 0, 2.5),
    point(1.2, 0, -2.9),
    point(6.8, 0, -8.2),
    point(10.3, 0, -9.2),
  ],
  objectives: ['extract'],
});
