import { LIGHT_PALETTE, LIGHT_ROLES, MATERIAL_KEYS, normalizeLevelDef, point, pose, shadowLane } from './LevelDef.js';

export const level03_LoadingBay = normalizeLevelDef({
  id: 'level03_loading_bay',
  title: 'Level 03 - Loading Bay',
  brief: 'A wide dock infiltration built around vehicle cover, catwalk silhouettes, and long amber kill lanes.',
  bounds: { w: 28, d: 22, h: 6.4 },
  extract: point(12.0, 0, -7.8),
  spawn: {
    p0: pose(-12.0, 0, 7.9, -0.82),
    p1: pose(-10.7, 0, 7.1, -0.74),
  },
  lights: [
    {
      id: 'loading-dock-entry-blue',
      x: -11.0,
      y: 4.2,
      z: 6.2,
      target: point(-10.2, 0.04, 5.2),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 12.5,
      range: 8,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'loading-lane-amber-key',
      x: -4.0,
      y: 5.45,
      z: 1.7,
      target: point(-2.4, 0.04, 1.1),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 20,
      range: 11.8,
      breakable: true,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'loading-truck-shadow-fill',
      x: 2.6,
      y: 3.6,
      z: 6.2,
      target: point(2.2, 0.04, 4.6),
      color: LIGHT_PALETTE.dimBlueGray,
      intensity: 8.5,
      range: 6.8,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'loading-catwalk-trap',
      x: 6.4,
      y: 5.65,
      z: -2.4,
      target: point(6.8, 0.04, -1.1),
      color: LIGHT_PALETTE.hotSodiumAmber,
      intensity: 18.5,
      range: 9.4,
      breakable: true,
      role: LIGHT_ROLES.trap,
    },
    {
      id: 'loading-office-green',
      x: 10.3,
      y: 1.7,
      z: 3.9,
      color: LIGHT_PALETTE.dirtyGreenBlack,
      intensity: 5.2,
      range: 5.8,
      breakable: false,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'loading-extract-cold',
      x: 11.6,
      y: 3.0,
      z: -6.8,
      target: point(12.0, 0.04, -7.8),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 10,
      range: 6.6,
      breakable: false,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'loading-yard-amber-wash',
      x: 0.8,
      y: 5.75,
      z: -7.6,
      target: point(1.7, 0.04, -6.6),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 15.5,
      range: 9.2,
      breakable: true,
      role: LIGHT_ROLES.trap,
    },
  ],
  shadowLanes: [
    shadowLane(point(-12.0, 0, 7.9), point(-6.5, 0, 5.2), 'dock lip under cold entry fixture'),
    shadowLane(point(-6.5, 0, 5.2), point(0.4, 0, 4.7), 'left side of parked box truck'),
    shadowLane(point(0.4, 0, 4.7), point(6.2, 0, 1.8), 'forklift gap under catwalk shadow'),
    shadowLane(point(6.2, 0, 1.8), point(11.5, 0, -7.2), 'final office wall to extract'),
  ],
  geometry: [
    { type: 'floor', id: 'loading-floor', x: 0, y: 0, z: 0, w: 28, d: 22, material: MATERIAL_KEYS.floor },
    { type: 'box', id: 'loading-ceiling-trusses', x: 0, y: 6.48, z: 0, w: 28, h: 0.16, d: 22, material: MATERIAL_KEYS.darkWall },
    { type: 'box', id: 'loading-west-wall', x: -14.15, y: 3.2, z: 0, w: 0.3, h: 6.4, d: 22.4, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'loading-east-wall', x: 14.15, y: 3.2, z: 0, w: 0.3, h: 6.4, d: 22.4, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'loading-north-wall', x: 0, y: 3.2, z: -11.15, w: 28, h: 6.4, d: 0.3, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'loading-south-wall-left', x: -8.5, y: 3.2, z: 11.15, w: 10.7, h: 6.4, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'loading-south-wall-right', x: 8.6, y: 3.2, z: 11.15, w: 10.8, h: 6.4, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'loading-south-dock-header', x: 0, y: 5.15, z: 11.15, w: 6.2, h: 2.5, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'catwalk', id: 'loading-north-catwalk', x: 0, y: 3.38, z: -8.6, w: 22.5, d: 2.05, yaw: 0, material: MATERIAL_KEYS.steel },
    { type: 'catwalk', id: 'loading-east-catwalk', x: 10.6, y: 3.38, z: -1.2, w: 2.05, d: 11.2, yaw: 0, material: MATERIAL_KEYS.steel },
    { type: 'stairs', id: 'loading-catwalk-stairs', x: 8.7, y: 0, z: 4.8, w: 2.0, h: 3.38, d: 7.2, yaw: 0.15, steps: 11, material: MATERIAL_KEYS.blackSteel },
    { type: 'box', id: 'loading-box-truck-body', x: -1.6, y: 1.35, z: 4.8, w: 6.8, h: 2.7, d: 2.55, material: MATERIAL_KEYS.vehicle, collider: true, occluder: true },
    { type: 'box', id: 'loading-box-truck-cab', x: 2.7, y: 1.05, z: 4.5, w: 2.1, h: 2.1, d: 2.3, material: MATERIAL_KEYS.vehicle, collider: true, occluder: true },
    { type: 'box', id: 'loading-van-cover', x: -7.3, y: 0.95, z: -1.7, w: 3.7, h: 1.9, d: 2.05, yaw: -0.08, material: MATERIAL_KEYS.vehicle, collider: true, occluder: true },
    { type: 'box', id: 'loading-forklift-body', x: 5.4, y: 0.62, z: 1.3, w: 2.0, h: 1.24, d: 1.25, yaw: 0.32, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'loading-forklift-mast', x: 6.3, y: 1.45, z: 1.55, w: 0.22, h: 2.9, d: 1.45, yaw: 0.32, material: MATERIAL_KEYS.steel, collider: true, occluder: true },
    { type: 'box', id: 'loading-pallet-stack-a', x: -10.0, y: 0.68, z: 2.6, w: 2.0, h: 1.36, d: 2.3, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'loading-pallet-stack-b', x: -5.0, y: 0.8, z: 6.9, w: 2.7, h: 1.6, d: 1.6, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'loading-pallet-stack-c', x: 6.9, y: 0.74, z: -4.9, w: 3.1, h: 1.48, d: 1.55, material: MATERIAL_KEYS.crate, collider: true, occluder: true },
    { type: 'box', id: 'loading-office-wall', x: 9.9, y: 1.5, z: 4.8, w: 4.0, h: 3.0, d: 0.28, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'loading-office-return', x: 7.95, y: 1.5, z: 2.95, w: 0.28, h: 3.0, d: 3.95, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'loading-dock-ramp', x: -9.4, y: 0.12, z: 9.1, w: 5.4, h: 0.24, d: 3.1, material: MATERIAL_KEYS.steel, collider: true, occluder: false },
    { type: 'box', id: 'loading-extract-frame-left', x: 11.2, y: 1.35, z: -9.15, w: 0.2, h: 2.7, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'loading-extract-frame-right', x: 12.9, y: 1.35, z: -9.15, w: 0.2, h: 2.7, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
  ],
  patrols: [
    [
      point(-10.0, 0, 4.8),
      point(-4.2, 0, 2.0),
      point(2.2, 0, 0.9),
      point(8.5, 0, -3.8),
      point(2.8, 0, -7.3),
      point(-7.8, 0, -2.0),
    ],
  ],
  coverPoints: [
    point(-10.4, 0, 2.7),
    point(-6.9, 0, -1.1),
    point(-1.2, 0, 5.9),
    point(3.0, 0, 4.0),
    point(5.3, 0, 1.9),
    point(7.1, 0, -4.4),
    point(10.4, 0, 4.2),
  ],
  shadowPoints: [
    point(-11.7, 0, 6.8),
    point(-5.8, 0, 4.7),
    point(0.6, 0, 5.0),
    point(5.9, 0, 2.1),
    point(8.8, 0, -5.9),
    point(11.9, 0, -7.6),
  ],
  objectives: ['extract'],
});
