import { LIGHT_PALETTE, LIGHT_ROLES, MATERIAL_KEYS, normalizeLevelDef, point, pose, shadowLane } from './LevelDef.js';

export const level02_Substation = normalizeLevelDef({
  id: 'level02_substation',
  title: 'Level 02 - Substation Switch House',
  brief: 'A service substation where the quiet route is lit one way, then the alarm kills that map and opens a harsher one.',
  bounds: { w: 28, d: 22, h: 5.2 },
  extract: point(11.6, 0, -8.2),
  spawn: {
    p0: pose(-11.4, 0, 8.3, -0.78),
    p1: pose(-10.0, 0, 7.6, -0.68),
  },
  lights: [
    {
      id: 'substation-entry-blue-fill',
      x: -10.5,
      y: 3.6,
      z: 6.4,
      target: point(-9.2, 0.04, 5.6),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 12,
      range: 7.8,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'substation-busway-key',
      x: -3.2,
      y: 4.55,
      z: 1.4,
      target: point(-2.4, 0.04, 0.4),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 19,
      range: 10.5,
      breakable: true,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'substation-transformer-trap',
      x: 4.5,
      y: 4.35,
      z: 3.4,
      target: point(5.4, 0.04, 2.5),
      color: LIGHT_PALETTE.hotSodiumAmber,
      intensity: 17.5,
      range: 8.3,
      breakable: true,
      role: LIGHT_ROLES.trap,
    },
    {
      id: 'substation-safe-hall-fill',
      x: 6.9,
      y: 3.15,
      z: -5.3,
      target: point(7.9, 0.04, -6.4),
      color: LIGHT_PALETTE.dimBlueGray,
      intensity: 10,
      range: 7.1,
      breakable: true,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'substation-breaker-green',
      x: -8.2,
      y: 1.45,
      z: -4.8,
      color: LIGHT_PALETTE.dirtyGreenBlack,
      intensity: 4.6,
      range: 5.2,
      breakable: false,
      role: LIGHT_ROLES.fill,
    },
    {
      id: 'substation-extract-amber',
      x: 11.5,
      y: 2.65,
      z: -7.6,
      target: point(11.6, 0.04, -8.2),
      color: LIGHT_PALETTE.sodiumAmber,
      intensity: 9.5,
      range: 6,
      breakable: false,
      role: LIGHT_ROLES.key,
    },
    {
      id: 'substation-alarm-crossfire-amber',
      x: 0.8,
      y: 4.65,
      z: -2.4,
      target: point(1.4, 0.04, -1.2),
      color: LIGHT_PALETTE.hotSodiumAmber,
      intensity: 22,
      range: 11.2,
      breakable: true,
      role: LIGHT_ROLES.alarm,
      enabled: false,
    },
    {
      id: 'substation-alarm-yard-cold',
      x: 8.8,
      y: 4.25,
      z: 1.1,
      target: point(7.0, 0.04, -0.1),
      color: LIGHT_PALETTE.coldBlueGray,
      intensity: 18,
      range: 10.4,
      breakable: true,
      role: LIGHT_ROLES.alarm,
      enabled: false,
    },
  ],
  shadowLanes: [
    shadowLane(point(-11.4, 0, 8.3), point(-6.6, 0, 1.8), 'quiet entry behind cable troughs'),
    shadowLane(point(-6.6, 0, 1.8), point(1.2, 0, -4.4), 'breaker island shadow before alarm'),
    shadowLane(point(1.2, 0, -4.4), point(10.6, 0, -8.0), 'safe hall route closes when alarm flips'),
    shadowLane(point(1.8, 0, 3.9), point(9.0, 0, 2.2), 'alarm-open transformer cut for assault push'),
  ],
  geometry: [
    { type: 'floor', id: 'substation-floor', x: 0, y: 0, z: 0, w: 28, d: 22, material: MATERIAL_KEYS.floor },
    { type: 'box', id: 'substation-ceiling', x: 0, y: 5.28, z: 0, w: 28, h: 0.16, d: 22, material: MATERIAL_KEYS.darkWall },
    { type: 'box', id: 'substation-west-wall', x: -14.15, y: 2.6, z: 0, w: 0.3, h: 5.2, d: 22.4, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'substation-east-wall', x: 14.15, y: 2.6, z: 0, w: 0.3, h: 5.2, d: 22.4, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'substation-north-wall', x: 0, y: 2.6, z: -11.15, w: 28, h: 5.2, d: 0.3, material: MATERIAL_KEYS.wall, collider: true, occluder: true },
    { type: 'box', id: 'substation-south-wall-left', x: -7.4, y: 2.6, z: 11.15, w: 12.7, h: 5.2, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'substation-south-wall-right', x: 9.4, y: 2.6, z: 11.15, w: 9.2, h: 5.2, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'substation-entry-lintel', x: 1.15, y: 4.0, z: 11.15, w: 6.0, h: 2.4, d: 0.3, material: MATERIAL_KEYS.darkWall, collider: true, occluder: true },
    { type: 'box', id: 'substation-cable-trough-a', x: -8.3, y: 0.42, z: 2.4, w: 5.9, h: 0.84, d: 0.76, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-cable-trough-b', x: -4.6, y: 0.42, z: -2.2, w: 0.85, h: 0.84, d: 6.0, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-breaker-bank-west', x: -9.4, y: 1.18, z: -5.4, w: 3.8, h: 2.36, d: 1.1, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-breaker-bank-east', x: -4.0, y: 1.18, z: -6.0, w: 3.6, h: 2.36, d: 1.1, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-transformer-a', x: 4.1, y: 1.22, z: 3.6, w: 3.8, h: 2.44, d: 2.8, material: MATERIAL_KEYS.steel, collider: true, occluder: true },
    { type: 'box', id: 'substation-transformer-b', x: 9.0, y: 1.22, z: 3.2, w: 3.0, h: 2.44, d: 2.4, material: MATERIAL_KEYS.steel, collider: true, occluder: true },
    { type: 'box', id: 'substation-control-desk', x: 1.0, y: 0.55, z: -5.3, w: 3.7, h: 1.1, d: 1.35, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-busbar-column-a', x: -1.1, y: 2.55, z: 1.1, w: 0.35, h: 5.1, d: 0.35, material: MATERIAL_KEYS.steel, collider: true, occluder: true },
    { type: 'box', id: 'substation-busbar-column-b', x: 2.1, y: 2.55, z: 1.0, w: 0.35, h: 5.1, d: 0.35, material: MATERIAL_KEYS.steel, collider: true, occluder: true },
    { type: 'shutter', id: 'shutter-safe-hall', x: 5.3, y: 1.45, z: -3.2, w: 0.28, h: 2.9, d: 3.2, material: MATERIAL_KEYS.blackSteel, open: true, collider: true, occluder: true },
    { type: 'shutter', id: 'shutter-transformer-cut', x: 6.4, y: 1.45, z: 0.6, w: 3.4, h: 2.9, d: 0.28, material: MATERIAL_KEYS.blackSteel, open: false, collider: true, occluder: true },
    { type: 'shutter', id: 'shutter-side-cage', x: -0.2, y: 1.45, z: 4.9, w: 0.28, h: 2.9, d: 3.5, material: MATERIAL_KEYS.blackSteel, open: false, collider: true, occluder: true },
    { type: 'box', id: 'substation-extract-frame-left', x: 10.75, y: 1.3, z: -9.45, w: 0.2, h: 2.6, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
    { type: 'box', id: 'substation-extract-frame-right', x: 12.55, y: 1.3, z: -9.45, w: 0.2, h: 2.6, d: 0.28, material: MATERIAL_KEYS.blackSteel, collider: true, occluder: true },
  ],
  patrols: [
    [
      point(-8.6, 0, 4.8),
      point(-2.8, 0, 1.2),
      point(4.2, 0, 1.6),
      point(8.9, 0, -4.7),
      point(0.5, 0, -6.5),
      point(-8.8, 0, -4.8),
    ],
  ],
  coverPoints: [
    point(-8.9, 0, 2.2),
    point(-4.5, 0, -2.9),
    point(2.7, 0, -5.4),
    point(4.7, 0, 3.9),
    point(9.4, 0, 3.1),
    point(10.8, 0, -7.2),
  ],
  shadowPoints: [
    point(-11.0, 0, 7.0),
    point(-6.4, 0, 1.2),
    point(-0.3, 0, -4.8),
    point(7.5, 0, -6.7),
    point(2.3, 0, 3.9),
  ],
  alarmLayout: {
    enableLightIds: ['substation-alarm-crossfire-amber', 'substation-alarm-yard-cold'],
    disableLightIds: ['substation-busway-key', 'substation-safe-hall-fill'],
    openShutters: ['shutter-transformer-cut', 'shutter-side-cage'],
    closeShutters: ['shutter-safe-hall'],
  },
  objectives: ['extract'],
});
